#!/usr/bin/env bash
# Writes "I am alive" to the /tmp/my_process file indefinitely.
#   Sleeps for two seconds between each message.

while true
do
  echo "I am alive" >> /tmp/my_process
  sleep 2
done
